### ISSUE TITLE
Empty Landscaper secrets config removes pre-existing secrets

### ISSUE THREAD

**Issue by james-masson** [Eneco/landscaper#101]
I'm using secrets management outside Landscaper.

My landscaper configurations have no reference to secrets.

A separately managed secret with the same name as the helm deployment will be silently removed by Landscaper, as it assumes it owns it.

eg.

```
name: af1-rmq
namespace: af1
release:
  chart: stuff/rabbitmq:0.6.8
configuration:
  mgt_hostname: af1-rmq
```

will produce.

```
-- Current af1-rmq
+++ Desired af1-rmq
@@ -36,8 +36,5 @@
     },
     "serviceType": "ClusterIP"
   },
-  "secrets": [
-    "rabbitmq-erlang-cookie",
-    "rabbitmq-password"
-  ]
+  "secrets": []
 }
```

Please consider having the ability to switch off the secrets management, as it can be dangerous.
