### ISSUE TITLE
multiple state in one file?

### ISSUE THREAD

**Issue by hiscal2015** [Eneco/landscaper#110]
Hi, 

Does landscaper support multiple states in one yaml file like this:
```
- name: my-component1
  release:
     chart: "example/chart:0.1.0"
     version: 0.1.0
- name: my-component2
  release:
     chart: "example/chart:0.2.0"
     version: 0.2.0
```
  
And, is it necessary to define a "version" parameter here? Because the chart will read version number from Chart.yaml.
