### ISSUE TITLE
Using secrets for Datadog chart

### ISSUE THREAD

**Issue by mazzy89** [Eneco/landscaper#62]
This is my state file for Datadog Chart:

```yaml
name: datadog
release:
  chart: stable/datadog:0.3.0
  version: 0.3.0
configuration:
  # Default values for datadog.
  image:
    repository: datadog/docker-dd-agent
    tag: latest
    pullPolicy: IfNotPresent

  datadog:
    ## You'll need to set this to your Datadog API key before the agent will run.
    ## ref: https://app.datadoghq.com/account/settings#agent/kubernetes
    ##
    apiKey: ""

    ## Set logging verbosity.
    ## ref: https://github.com/DataDog/docker-dd-agent#environment-variables
    ##
    logLevel: WARNING

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 512Mi
secrets:
  - api-key
```
and this is how run landscraper
```bash
API_KEY=343242342342  landscaper apply --dir charts --dry-run --namespace default
```
Unfortunately the secret API_KEY is not applied. Any idea?
