### ISSUE TITLE
Get rid of Release.Version

### ISSUE THREAD

**Issue by rollulus** [Eneco/landscaper#73]
see #58, #66

**Comment by philipbjorge** [comment]
@rollulus -- Cool if I take this on?

It sounds like we want to remove it, rather than make it optional?

**Comment by rollulus** [comment]
I'm cool with that, @philipbjorge, thanks :+1: 

Maybe we should make it optional instead of totally removing it, just in case.

While removing / making it optional, I was considering to get rid of `release` though, moving `chart` and the now optional `version` up one level, e.g.:
```yaml
name: hello-world
chart: local/hello-world:0.1.0
configuration:
  message: Hello, Landscaped world!
```
Is that something you'd like to do as well? I'm looking forward to your PR, thanks!
